// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mjZeMATppmSbXn8kNP-JFDK7IcKwg9s',
    appId: '1:371898205121:web:69dd7b0b44d7ba5bed6540',
    messagingSenderId: '371898205121',
    projectId: 'flutterapplication-77c19',
    authDomain: 'flutterapplication-77c19.firebaseapp.com',
    storageBucket: 'flutterapplication-77c19.firebasestorage.app',
    measurementId: 'G-9WP5RR37PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN5mKfdvZ32uYzFnEoyJJfbsII7UJwbYU',
    appId: '1:371898205121:android:5d70d87111544f10ed6540',
    messagingSenderId: '371898205121',
    projectId: 'flutterapplication-77c19',
    storageBucket: 'flutterapplication-77c19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa-MrebMPTSDJVq-s8OHo6Fp2V-KZxysQ',
    appId: '1:371898205121:ios:6201088f69f308d6ed6540',
    messagingSenderId: '371898205121',
    projectId: 'flutterapplication-77c19',
    storageBucket: 'flutterapplication-77c19.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa-MrebMPTSDJVq-s8OHo6Fp2V-KZxysQ',
    appId: '1:371898205121:ios:6201088f69f308d6ed6540',
    messagingSenderId: '371898205121',
    projectId: 'flutterapplication-77c19',
    storageBucket: 'flutterapplication-77c19.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-mjZeMATppmSbXn8kNP-JFDK7IcKwg9s',
    appId: '1:371898205121:web:a2c5934ae74903f1ed6540',
    messagingSenderId: '371898205121',
    projectId: 'flutterapplication-77c19',
    authDomain: 'flutterapplication-77c19.firebaseapp.com',
    storageBucket: 'flutterapplication-77c19.firebasestorage.app',
    measurementId: 'G-RSWKTPJN4X',
  );
}
